apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
  selector:
    app: my-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: #{ecr_image_uri}
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        volumeMounts:
        - name: mountpoint-s3
          mountPath: /mountpoint-s3
      volumes:
      - name: mountpoint-s3
        persistentVolumeClaim:
          claimName: mountpoint-s3-pvc