apiVersion: v1
kind: PersistentVolume
metadata:
  name: mountpoint-s3-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-overwrite
    - region us-east-1
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: s3-mountpoint-327270246675
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mountpoint-s3-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
  volumeName: mountpoint-s3-pv
